### PR TITLE
docs: fix order

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
Fix docs order and include container methods

## Related issues

-

### CODE REVIEW

**Comment by mdelapenya** [comment]
@mashail I merged my local branch with current main, that's why you see commits from yugabyte.

My recommendation for OSS contributions would be always use a new branch, not create the commits on main.

**Comment by mdelapenya** [comment]
@mashail I'm closing this one in favour of the PR in the upstream repo, which includes all your work plus the refinements regarding the docs and CI.

Thanks for your time!

**Comment by mashail** [comment]
> @mashail I merged my local branch with current main, that's why you see commits from yugabyte.
> 
> My recommendation for OSS contributions would be always use a new branch, not create the commits on main.

Sure

**Comment by mashail** [comment]
> @mashail I'm closing this one in favour of the PR in the upstream repo, which includes all your work plus the refinements regarding the docs and CI.
> 
> Thanks for your time!

Ok let me rebase my main branch

**Pull request closed without merging**
